language: julia
os: # WARNING: any change here must also be done in docs/make.jl
  - linux
  - osx
julia: # WARNING: any change here must also be done in docs/make.jl
#  - release
 - 0.6
env:
 - DRAW_FIG="false"
   DOCUMENTER_DEBUG="true"
notifications:
  email: false

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git r-base r-base-dev r-recommended -y; fi

  # osx
  # faster than using homebrew/science tap
  # but no permalink to release download
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg R-*.pkg -target /; fi

after_success:
  - julia -e 'Pkg.clone("https://github.com/pbastide/Documenter.jl")'
#  - julia -e 'Pkg.checkout("Documenter", "release-0.11")'
  - julia -e 'Pkg.add("Cairo")'
  - julia -e 'Pkg.add("Fontconfig")'
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm /Users/travis/.julia/lib/v$TRAVIS_JULIA_VERSION/Compose.ji; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rm /home/travis/.julia/lib/v$TRAVIS_JULIA_VERSION/Compose.ji; fi
  - julia -e 'Pkg.add("Weave")'
  - julia -e 'cd(Pkg.dir("PhyloNetworks")); include(joinpath("docs", "make.jl"))'
