language: julia
os: # WARNING: any change here must also be done in docs/make.jl
  - linux
  - osx
julia: # WARNING: any change here must also be done in docs/make.jl
# - release
  - 0.6
env:
  - DRAW_FIG="false"
    DOCUMENTER_DEBUG="true"
notifications:
  email: false

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git r-base r-base-dev r-recommended -y; fi

  # osx
  # faster than using homebrew/science tap
  # but no permalink to release download
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg R-*.pkg -target /; fi

  # Fix NLopt. This line should be removed when a a new release of NLopt is out.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then julia -e 'Pkg.clone("https://github.com/JuliaOpt/NLopt.jl"); Pkg.build("NLopt")'; fi

  # Binaries
# - export PATH=$HOME/.local/bin:$PATH

after_success:
  # Build doc
  - chmod +x docs/make.sh
  - ./docs/make.sh
  # Code coverage
  - julia -e 'cd(Pkg.dir("PhyloNetworks")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
