language: julia
os: # WARNING: any change here must also be done in docs/make.jl
  - linux
  - osx
julia: # WARNING: any change here must also be done in docs/make.jl
# - release
  - 0.6
env:
  - DRAW_FIG="false"
    #DOCUMENTER_DEBUG="true"
notifications:
  email: false
## Following 4 lines are taken from here:
# https://github.com/JuliaOpt/NLopt.jl/blob/master/.travis.yml#L10
# They're meant to fix the NLopt build on Linux.
addons:
    apt: # apt-get for linux
        packages:
            - libnlopt0 # We install it this way to be able to run Travis with `sudo: false`

  # Fix NLopt. This line should be removed when a a new release of NLopt is out.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then julia -e 'Pkg.clone("https://github.com/JuliaOpt/NLopt.jl"); Pkg.build("NLopt")'; fi

  # Binaries
# - export PATH=$HOME/.local/bin:$PATH

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("PhyloNetworks")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("PhyloNetworks")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build doc
  - chmod +x docs/make.sh
  - ./docs/make.sh
